# This is a basic workflow to help you get started with Actions

name: sync playlist

# Controls when the workflow will run
on:
  schedule:
    - cron: '0 0 * * *'

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: checkout repo
        uses: actions/checkout@v2
      - name: setup python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'
          
      - name: pip install
        run: pip install requests
        
      - name: execute py script
        env:
          BASE_64: ${{ secrets.BASE_64 }}
          SPOTIFY_REFRESH_TOKEN: ${{ secrets.SPOTIFY_REFRESH_TOKEN }}
          SPOTIFY_USER_ID: ${{ secrets.SPOTIFY_USER_ID }}
        run: python main.py
